alias: encender luz
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.esp32_iot1_boton
    from: "off"
    to: "on"
condition: []
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.esp32_iot1_led
mode: single

