alias: encender ventilador
description: ""
trigger:
  - platform: numeric_state
    entity_id: switch.esp32_iot1_relÉ
    above: 20
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.esp32_iot1_relÉ
mode: single
